using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

public class RightWeaponController : MonoBehaviour
{
    [Header("weapon")]
    //weaponã‚’ãƒªã‚¹ãƒˆã«
    private List<GameObject> weapons = new List<GameObject> ();

    
    [SerializeField] private GameObject rightController;
    //å‰£ã®prefab
    [SerializeField] private GameObject sord;
    //éŠƒã®prefab
    [SerializeField] private GameObject gun;
    //icepickã®prefab
    [SerializeField] private GameObject icePick;
    //ç¾åœ¨ã®weaponã‚’ç™»éŒ²
    private GameObject currentWeapon;
    //è¦ªã®ä½ç½®ã‚’å–å¾—ã™ã‚‹ãŸã‚ã«
    private Transform parent;
    //æ­¦å™¨ã‚’å¤‰æ›´ã§ãã‚‹ã‚ˆã†ã«
    private bool changeable = true;
    //ç¾åœ¨ã®æ­¦å™¨ã®ç•ªå·ã‚’æŠŠæ¡
    private int weaponCnt = 0;

    private PlayerInputAction inputActions;

    private void Awake()
    {
        //æ­¦å™¨ã‚’ç™»éŒ²
        weapons.Add(rightController);
        weapons.Add(sord);
        weapons.Add(gun);
        weapons.Add (icePick);
        parent = this.transform;
        
        //ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼å³ã®ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼
        currentWeapon = Instantiate(rightController, parent);

        inputActions = new PlayerInputAction();
    }

    // private void Update()
    // {
    //     if (CheckView())
    //     {
    //         ChangeWeapon();
    //     }
    // }

    //gameviewã®ãŒå‡ºã¦ã„ã‚‹ã‹ç¢ºèª
    private bool CheckView()
    {
        GameObject Gameview = GameObject.FindWithTag("GameView");
        if (Gameview != null)
        {
            //Debug.Log("gameviewok");
            return true;
        }
        else
        {
            return false;
        }
    }

    public void ChangeWeapon(InputAction.CallbackContext context)
    {
        
        //å³ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼ã®ã‚°ãƒªãƒƒãƒ—ã‚’æŠ¼ã—ãŸã‚‰æ­¦å™¨ãŒå…¥ã‚Œæ›¿ã‚ã‚‹ã‚ˆã†ã«
        // if (OVRInput.Get(OVRInput.Button.SecondaryHandTrigger)&&changeable)
        if(context.performed&&changeable)
        {
            Debug.Log(weaponCnt);
            changeable = false;
         
            //ï¿½Eï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½íœ
            Destroy(currentWeapon);
            //ï¿½ï¿½ï¿½ğ¶ï¿½
            currentWeapon = Instantiate(weapons[weaponCnt], parent);
            Debug.Log("change");
            weaponCnt++;
          

        }
        // else if (OVRInput.GetUp(OVRInput.Button.SecondaryHandTrigger))
        else if (context.canceled)
        {
            //ï¿½Eï¿½ï¿½ï¿½wï¿½Ìƒgï¿½ï¿½ï¿½Kï¿½[ï¿½ï¿½ï¿½ã‚°ï¿½ï¿½ï¿½ï¿½tureï¿½ï¿½
            changeable=true;
            //cntï¿½ï¿½ï¿½Zï¿½bï¿½g
            if (weaponCnt == weapons.Count )
            {
                weaponCnt = 0;
            }
        }
   
    }

    public void ResetController()
    {
        Destroy((currentWeapon));
        Instantiate(rightController, parent);
    }
   
    private void OnEnable()
    {
        inputActions.Enable();
        inputActions.Game.SwitchWeapon.performed += ChangeWeapon;
        
        if (CheckView())
        {
            inputActions.Game.SwitchWeapon.performed += ChangeWeapon;
        }
    }

    private void OnDisable()
    {
        inputActions.Disable();
        inputActions.Game.SwitchWeapon.performed -= ChangeWeapon;
    }
}
